name: 'ecommerce_elt'
version: '1.0.0'
profile: 'ecommerce_elt'

model-paths: ["models"]
macro-paths: ["macros"]

models:
  ecommerce_elt:
    staging:
      +materialized: view
      +schema: staging      # -> schéma "staging" (voir macro generate_schema_name)
    marts:
      +materialized: table
      +schema: marts        # -> schéma "marts", ce que consomme Power BI
